// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingApi.infrastructure.Data;

#nullable disable

namespace WeddingApi.infrastructure.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    partial class WeddingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeddingApi.core.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WeddingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WeddingTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("WeddingApi.core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrideName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BridePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BudgetCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroomPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WeddingApi.core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("WeddingApi.core.Entities.ServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceFrom")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "قاعات الأفراح",
                            Description = "أفخم قاعات الأفراح في القاهرة",
                            IsActive = true,
                            Location = "مدينة نصر، القاهرة",
                            Name = "بالاس ويدينج هول",
                            Phone = "01001234567",
                            PriceFrom = 30000m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 234
                        },
                        new
                        {
                            Id = 2,
                            Category = "التصوير والفيديو",
                            Description = "تصوير احترافي لحفلات الزفاف",
                            IsActive = true,
                            Location = "المعادي، القاهرة",
                            Name = "ستوديو ليلى فوتو",
                            Phone = "01112345678",
                            PriceFrom = 8000m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 189
                        },
                        new
                        {
                            Id = 3,
                            Category = "تنسيق الزهور",
                            Description = "تنسيق زهور وديكور للأفراح",
                            IsActive = true,
                            Location = "الزمالك، القاهرة",
                            Name = "فلاورز باي نور",
                            Phone = "01223456789",
                            PriceFrom = 5000m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 156
                        },
                        new
                        {
                            Id = 4,
                            Category = "الكيترينج",
                            Description = "أشهى المأكولات لحفل زفافك",
                            IsActive = true,
                            Location = "التجمع الخامس",
                            Name = "لافوشيه كيترينج",
                            Phone = "01334567890",
                            PriceFrom = 120m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 312
                        },
                        new
                        {
                            Id = 5,
                            Category = "فساتين الزفاف",
                            Description = "أجمل فساتين الزفاف",
                            IsActive = true,
                            Location = "المهندسين، القاهرة",
                            Name = "جلوري برايدال",
                            Phone = "01445678901",
                            PriceFrom = 5000m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 421
                        },
                        new
                        {
                            Id = 6,
                            Category = "الموسيقى",
                            Description = "فرقة موسيقية متخصصة في حفلات الزفاف",
                            IsActive = true,
                            Location = "وسط البلد، القاهرة",
                            Name = "موسيقار بند",
                            Phone = "01556789012",
                            PriceFrom = 8000m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 98
                        },
                        new
                        {
                            Id = 7,
                            Category = "كوافير ومكياج",
                            Description = "متخصصون في إطلالات العرايس",
                            IsActive = true,
                            Location = "المعادي، القاهرة",
                            Name = "جلام بيوتي",
                            Phone = "01667890123",
                            PriceFrom = 3000m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 203
                        });
                });

            modelBuilder.Entity("WeddingApi.core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$pTMvOtyhcOiDXHiCqzIkdeN2EugPLJka.OaO0dB2N95VdHv1kAFMe",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WeddingApi.core.Entities.Booking", b =>
                {
                    b.HasOne("WeddingApi.core.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WeddingApi.core.Entities.Payment", b =>
                {
                    b.HasOne("WeddingApi.core.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("WeddingApi.core.Entities.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WeddingApi.core.Entities.Client", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
